package main

import (
	"encoding/json"
	"fmt"
	"math/big"
	"os"
	"path/filepath"
	"strings"

	"github.com/consensys/gnark-crypto/ecc"
	frbn254 "github.com/consensys/gnark-crypto/ecc/bn254/fr"
	"github.com/consensys/gnark/backend"
	"github.com/consensys/gnark/backend/groth16"
	groth16bn254 "github.com/consensys/gnark/backend/groth16/bn254"
	"github.com/consensys/gnark/backend/solidity"
	"github.com/consensys/gnark/frontend"
	"github.com/consensys/gnark/frontend/cs/r1cs"

	"gnark-playground/internal/circuit"
)

type proofArtifact struct {
	Proof        []string `json:"proof"`
	PublicInputs []string `json:"publicInputs"`
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(1)
	}
	fmt.Println("generated verifier and fixtures")
}

func run() error {
	ccs, err := frontend.Compile(ecc.BN254.ScalarField(), r1cs.NewBuilder, &circuit.MulCircuit{})
	if err != nil {
		return fmt.Errorf("compile circuit: %w", err)
	}

	pk, vk, err := groth16.Setup(ccs)
	if err != nil {
		return fmt.Errorf("setup groth16: %w", err)
	}

	assignment := &circuit.MulCircuit{
		A: 6,
		B: 7,
		C: 42,
	}
	fullWitness, err := frontend.NewWitness(assignment, ecc.BN254.ScalarField())
	if err != nil {
		return fmt.Errorf("build full witness: %w", err)
	}
	publicWitness, err := fullWitness.Public()
	if err != nil {
		return fmt.Errorf("build public witness: %w", err)
	}

	proof, err := groth16.Prove(ccs, pk, fullWitness, solidity.WithProverTargetSolidityVerifier(backend.GROTH16))
	if err != nil {
		return fmt.Errorf("prove: %w", err)
	}

	if err := groth16.Verify(proof, vk, publicWitness, solidity.WithVerifierTargetSolidityVerifier(backend.GROTH16)); err != nil {
		return fmt.Errorf("verify: %w", err)
	}

	bnProof, ok := proof.(*groth16bn254.Proof)
	if !ok {
		return fmt.Errorf("unexpected proof type %T", proof)
	}
	bnVK, ok := vk.(*groth16bn254.VerifyingKey)
	if !ok {
		return fmt.Errorf("unexpected verifying key type %T", vk)
	}
	pubVector, ok := publicWitness.Vector().(frbn254.Vector)
	if !ok {
		return fmt.Errorf("unexpected public witness vector type %T", publicWitness.Vector())
	}

	contractsDir := filepath.Join("..", "onchain", "contracts")
	testDir := filepath.Join("..", "onchain", "test")
	artifactsDir := filepath.Join("..", "artifacts")

	if err := os.MkdirAll(contractsDir, 0o755); err != nil {
		return fmt.Errorf("create contracts dir: %w", err)
	}
	if err := os.MkdirAll(testDir, 0o755); err != nil {
		return fmt.Errorf("create test dir: %w", err)
	}
	if err := os.MkdirAll(artifactsDir, 0o755); err != nil {
		return fmt.Errorf("create artifacts dir: %w", err)
	}

	if err := writeVerifier(filepath.Join(contractsDir, "Verifier.sol"), bnVK); err != nil {
		return err
	}

	proofWords, err := proofToU256Words(bnProof)
	if err != nil {
		return err
	}
	publicInputs := vectorToDecimal(pubVector)

	if err := writeFixture(filepath.Join(testDir, "GnarkFixture.sol"), proofWords, publicInputs); err != nil {
		return err
	}
	if err := writeJSON(filepath.Join(artifactsDir, "basic_proof.json"), proofWords, publicInputs); err != nil {
		return err
	}

	return nil
}

func writeVerifier(path string, vk *groth16bn254.VerifyingKey) error {
	f, err := os.Create(path)
	if err != nil {
		return fmt.Errorf("create verifier file: %w", err)
	}
	defer f.Close()

	if err := vk.ExportSolidity(f, solidity.WithPragmaVersion("^0.8.20")); err != nil {
		return fmt.Errorf("export solidity verifier: %w", err)
	}
	return nil
}

func proofToU256Words(proof *groth16bn254.Proof) ([]string, error) {
	raw := proof.MarshalSolidity()
	if len(raw) < 8*32 {
		return nil, fmt.Errorf("proof too short: %d bytes", len(raw))
	}

	out := make([]string, 8)
	for i := 0; i < 8; i++ {
		chunk := raw[i*32 : (i+1)*32]
		n := new(big.Int).SetBytes(chunk)
		out[i] = n.String()
	}
	return out, nil
}

func vectorToDecimal(v frbn254.Vector) []string {
	out := make([]string, len(v))
	for i := range v {
		var n big.Int
		v[i].BigInt(&n)
		out[i] = n.String()
	}
	return out
}

func writeFixture(path string, proof, publicInputs []string) error {
	const tpl = `// Code generated by zk/cmd/gnark-basic. DO NOT EDIT.
pragma solidity ^0.8.20;

library GnarkFixture {
    function proof() internal pure returns (uint256[8] memory p) {
        p = [%s];
    }

    function publicInputs() internal pure returns (uint256[%d] memory input) {
        input = [%s];
    }
}
`
	content := fmt.Sprintf(tpl, u256LiteralList(proof), len(publicInputs), u256LiteralList(publicInputs))
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return fmt.Errorf("write fixture %s: %w", path, err)
	}
	return nil
}

func writeJSON(path string, proof, publicInputs []string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("create artifacts dir: %w", err)
	}
	data, err := json.MarshalIndent(proofArtifact{
		Proof:        proof,
		PublicInputs: publicInputs,
	}, "", "  ")
	if err != nil {
		return fmt.Errorf("marshal proof artifact: %w", err)
	}
	if err := os.WriteFile(path, data, 0o644); err != nil {
		return fmt.Errorf("write proof artifact: %w", err)
	}
	return nil
}

func u256LiteralList(values []string) string {
	parts := make([]string, len(values))
	for i, v := range values {
		parts[i] = fmt.Sprintf("uint256(%s)", v)
	}
	return strings.Join(parts, ", ")
}
